[build]
  base    = "college-comparison-app"
  command = "npm install && npm run build"
  publish = "college-comparison-app/dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
